//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalCriminal.CriminalWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalWCFService.ISearchCriminalService")]
    public interface ISearchCriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchCriminalService/SearchCriminal", ReplyAction="http://tempuri.org/ISearchCriminalService/SearchCriminalResponse")]
        NationalCriminal.WCF.ResultResponse SearchCriminal(string toEmail, string name, System.Nullable<int> ageFrom, System.Nullable<int> ageTo, System.Nullable<int> heightFrom, System.Nullable<int> heightTo, System.Nullable<int> weightFrom, System.Nullable<int> weightTo, System.Nullable<int> NationalityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchCriminalService/SearchCriminal", ReplyAction="http://tempuri.org/ISearchCriminalService/SearchCriminalResponse")]
        System.Threading.Tasks.Task<NationalCriminal.WCF.ResultResponse> SearchCriminalAsync(string toEmail, string name, System.Nullable<int> ageFrom, System.Nullable<int> ageTo, System.Nullable<int> heightFrom, System.Nullable<int> heightTo, System.Nullable<int> weightFrom, System.Nullable<int> weightTo, System.Nullable<int> NationalityId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchCriminalServiceChannel : NationalCriminal.CriminalWCFService.ISearchCriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCriminalServiceClient : System.ServiceModel.ClientBase<NationalCriminal.CriminalWCFService.ISearchCriminalService>, NationalCriminal.CriminalWCFService.ISearchCriminalService {
        
        public SearchCriminalServiceClient() {
        }
        
        public SearchCriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchCriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchCriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchCriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NationalCriminal.WCF.ResultResponse SearchCriminal(string toEmail, string name, System.Nullable<int> ageFrom, System.Nullable<int> ageTo, System.Nullable<int> heightFrom, System.Nullable<int> heightTo, System.Nullable<int> weightFrom, System.Nullable<int> weightTo, System.Nullable<int> NationalityId) {
            return base.Channel.SearchCriminal(toEmail, name, ageFrom, ageTo, heightFrom, heightTo, weightFrom, weightTo, NationalityId);
        }
        
        public System.Threading.Tasks.Task<NationalCriminal.WCF.ResultResponse> SearchCriminalAsync(string toEmail, string name, System.Nullable<int> ageFrom, System.Nullable<int> ageTo, System.Nullable<int> heightFrom, System.Nullable<int> heightTo, System.Nullable<int> weightFrom, System.Nullable<int> weightTo, System.Nullable<int> NationalityId) {
            return base.Channel.SearchCriminalAsync(toEmail, name, ageFrom, ageTo, heightFrom, heightTo, weightFrom, weightTo, NationalityId);
        }
    }
}
